### PR TITLE
Added logical operations program like AND, OR, X-OR and NOT

### PR DESCRIPTION
**Pull request by swastik1308**

### CODE REVIEW

**Review by khannishat67 — CHANGES_REQUESTED** [review]
Please provide comments within the code for people to know what the code does.

**Comment by swastik1308** [comment]
sure..will make the changes

**Comment by swastik1308** [comment]
Have made the necessary changes. Do reach out if any further changes are to
be made

**Review by khannishat67 — APPROVED** [review]

**Comment by axayjha** [comment]
Thanks for the contribution. 
ASM comments start with semi-colon, will update that.

**Pull request merged**
